nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs

npmScopes:
  gfour:
    npmRegistryServer: "https://gitlab.com/api/v4/packages/npm/"
    npmPublishRegistry: "https://gitlab.com/api/v4/projects/33359583/packages/npm/"